embedding_configs:
- api_key: ${OPENAI_API_KEY}
  batch_size: 100
  model: text-embedding-ada-002
  name: primary_embedding
  provider: openai
llm_configs:
- api_key: ${OPENAI_API_KEY}
  max_tokens: 2000
  model: gpt-4
  name: primary_llm
  provider: openai
  temperature: 0.7
- api_key: ${SILICONFLOW_API_KEY}
  max_tokens: 1500
  model: qwen-turbo
  name: backup_llm
  provider: siliconflow
  temperature: 0.8
