# RAG Knowledge QA System - Performance Configuration

# Application Performance Configuration
application:
  # Worker configuration
  workers:
    count: 4
    max_requests: 1000
    max_requests_jitter: 50
    timeout: 300
    keep_alive: 2
    preload_app: true
  
  # Thread configuration
  threads:
    min_threads: 1
    max_threads: 8
    thread_timeout: 30
  
  # Memory management
  memory:
    max_memory_per_worker: "1GB"
    garbage_collection_threshold: 0.8
    memory_profiling: false

# Database Performance Configuration
database:
  # Connection pooling
  connection_pool:
    pool_size: 20
    max_overflow: 30
    pool_timeout: 30
    pool_recycle: 3600
    pool_pre_ping: true
  
  # Query optimization
  query_optimization:
    statement_timeout: 30000  # 30 seconds
    lock_timeout: 10000       # 10 seconds
    idle_in_transaction_timeout: 60000  # 1 minute
    enable_query_cache: true
    query_cache_size: "256MB"
  
  # Indexing strategy
  indexing:
    auto_create_indexes: true
    analyze_threshold: 1000
    vacuum_threshold: 0.2
    maintenance_work_mem: "256MB"

# Vector Database Performance Configuration
vector_database:
  # Chroma configuration
  chroma:
    batch_size: 100
    max_batch_size: 1000
    persist_interval: 300  # 5 minutes
    index_type: "hnsw"
    
    # HNSW parameters
    hnsw:
      m: 16
      ef_construction: 200
      ef_search: 100
      max_connections: 16
  
  # Search optimization
  search:
    cache_enabled: true
    cache_size: 1000
    cache_ttl: 3600  # 1 hour
    parallel_search: true
    max_parallel_queries: 4

# Caching Configuration
caching:
  # Redis configuration
  redis:
    max_connections: 50
    connection_pool_size: 20
    socket_timeout: 5
    socket_connect_timeout: 5
    retry_on_timeout: true
    health_check_interval: 30
  
  # Cache strategies
  strategies:
    # Document cache
    documents:
      enabled: true
      ttl: 3600  # 1 hour
      max_size: 1000
      eviction_policy: "lru"
    
    # Embedding cache
    embeddings:
      enabled: true
      ttl: 86400  # 24 hours
      max_size: 10000
      eviction_policy: "lru"
    
    # Search results cache
    search_results:
      enabled: true
      ttl: 1800  # 30 minutes
      max_size: 5000
      eviction_policy: "lru"
    
    # QA results cache
    qa_results:
      enabled: true
      ttl: 3600  # 1 hour
      max_size: 2000
      eviction_policy: "lru"

# API Performance Configuration
api:
  # Request handling
  request_handling:
    max_request_size: 104857600  # 100MB
    request_timeout: 60
    keep_alive_timeout: 5
    max_concurrent_requests: 100
    request_queue_size: 1000
  
  # Response optimization
  response_optimization:
    compression_enabled: true
    compression_level: 6
    compression_min_size: 1024
    etag_enabled: true
    last_modified_enabled: true
  
  # Async processing
  async_processing:
    enabled: true
    max_async_tasks: 50
    task_timeout: 300
    result_ttl: 3600

# File Processing Performance Configuration
file_processing:
  # Parallel processing
  parallel_processing:
    enabled: true
    max_workers: 4
    chunk_processing_batch_size: 10
    max_concurrent_uploads: 5
  
  # Memory optimization
  memory_optimization:
    streaming_enabled: true
    buffer_size: 8192
    max_memory_usage: "512MB"
    temp_file_threshold: 10485760  # 10MB
  
  # Processing timeouts
  timeouts:
    text_extraction: 120
    chunking: 60
    embedding_generation: 300
    vector_storage: 180

# LLM Performance Configuration
llm:
  # Request optimization
  request_optimization:
    batch_requests: true
    max_batch_size: 10
    request_timeout: 60
    retry_attempts: 3
    retry_delay: 1
    exponential_backoff: true
  
  # Response caching
  response_caching:
    enabled: true
    cache_key_strategy: "content_hash"
    ttl: 3600  # 1 hour
    max_cache_size: 1000
  
  # Connection pooling
  connection_pooling:
    enabled: true
    pool_size: 10
    max_pool_size: 20
    pool_timeout: 30

# Monitoring Performance Configuration
monitoring:
  # Metrics collection
  metrics_collection:
    enabled: true
    collection_interval: 15  # seconds
    retention_period: 2592000  # 30 days
    aggregation_interval: 300  # 5 minutes
  
  # Performance metrics
  performance_metrics:
    - name: "request_duration"
      type: "histogram"
      buckets: [0.1, 0.5, 1.0, 2.0, 5.0, 10.0]
    
    - name: "request_rate"
      type: "counter"
    
    - name: "error_rate"
      type: "counter"
    
    - name: "memory_usage"
      type: "gauge"
    
    - name: "cpu_usage"
      type: "gauge"
    
    - name: "database_connections"
      type: "gauge"
    
    - name: "cache_hit_rate"
      type: "gauge"

# Resource Limits Configuration
resource_limits:
  # CPU limits
  cpu:
    max_cpu_percent: 80
    cpu_throttling_enabled: true
    cpu_affinity: []
  
  # Memory limits
  memory:
    max_memory_usage: "2GB"
    memory_swap_enabled: false
    oom_kill_disable: false
  
  # Disk I/O limits
  disk_io:
    max_read_iops: 1000
    max_write_iops: 500
    max_read_bps: 104857600   # 100MB/s
    max_write_bps: 52428800   # 50MB/s
  
  # Network limits
  network:
    max_bandwidth: 1073741824  # 1GB/s
    max_connections: 1000
    connection_timeout: 30

# Optimization Strategies
optimization:
  # Database optimization
  database_optimization:
    enable_query_planner: true
    auto_vacuum: true
    auto_analyze: true
    checkpoint_segments: 32
    wal_buffers: "16MB"
    shared_buffers: "256MB"
    effective_cache_size: "1GB"
  
  # Application optimization
  application_optimization:
    lazy_loading: true
    connection_reuse: true
    batch_operations: true
    async_operations: true
    result_streaming: true
  
  # System optimization
  system_optimization:
    kernel_optimization: true
    tcp_optimization: true
    file_descriptor_limits: 65536
    process_limits: 32768

# Load Balancing Configuration
load_balancing:
  enabled: false  # Enable for multi-instance deployments
  
  strategy: "round_robin"  # round_robin, least_connections, ip_hash
  
  health_checks:
    enabled: true
    interval: 30
    timeout: 10
    unhealthy_threshold: 3
    healthy_threshold: 2
  
  sticky_sessions:
    enabled: false
    cookie_name: "SERVERID"
    cookie_ttl: 3600

# Auto-scaling Configuration
auto_scaling:
  enabled: false  # Enable for cloud deployments
  
  metrics:
    cpu_threshold: 70
    memory_threshold: 80
    request_rate_threshold: 1000
  
  scaling_policy:
    min_instances: 2
    max_instances: 10
    scale_up_cooldown: 300
    scale_down_cooldown: 600
    scale_up_step: 1
    scale_down_step: 1